apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarysvc-k8s-deployment
spec:
  selector:
    matchLabels:
      app: librarysvc-k8s-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: librarysvc-k8s-deployment
    spec:
      containers:
        - name: librarysvc-k8s-deployment
          image: library-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080