version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
    ports:
      - "3306:3306"

  library-svc:
    image: library-svc
    build:
      context: .
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://localhost:3306/library_db
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpassword