apiVersion: v1
kind: Service
metadata:
  name: librarysvc-k8s-service
spec:
  selector:
    app: librarysvc-k8s-deployment
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort