spring:
  application:
    name: library-svc
  datasource:
    url: jdbc:mariadb://localhost:3306/library_db
    username: dbuser
    password: dbuser
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
